### ISSUE TITLE
First UTX after reset does not reply +OK

### ISSUE THREAD

**Issue by jpbaltazar** [hardwario/lora-modem#144]
After sending the first message after a reset, the modem never responds `+OK`.

I've verified the issue with an Oscilloscope.

Settings:
- EU868
- Class A
- OTAA
- Adaptable datarate enabled
- Dutycycle disabled

## Reproducing this issue
- Reset the modem
- Use UTX
- Await +OK

### Expected result:
`+EVENT=0,0\r\n\r\n+OK\r\n`

### Result:
`+EVENT=0,0\r\n`

**Comment by janakj** [comment]
Thanks for reporting this. This might be a bug introduced in the recent commits. I will check this next week.

**Comment by janakj** [comment]
Fixed in 1.4.1
